# Who is hit hardest by Inflation?
**Team Name:** Inflators
- Sanjana Devakumaran *(sanjud)*
- Sanjna Rachakonda *(sanjnarachakonda)*
- Tommy Ayers *(tlayers21)*
- Johnson Hwang *(hjohnson22)*
## Project Introduction
This project will investigate which groups are hit the hardest by inflation in the United States. We will evaluate and compare inflation trends with wage changes across different income levels and industries to understand how inflation affects different parts of the population.
## Research Questions
1. Does inflation affect low-income groups more severely than high-income ones?
2. Do wages keep up with inflation across different industries?
3. Are certain geographical regions hit harder by inflation than others?
## Potential Data Sources
- FRED - Historical Wages With and Without Inflation: https://fred.stlouisfed.org/tags/series?t=inflation;wages
- Atlanta FED - Wage Growth: https://www.atlantafed.org/research-and-data/data/wage-growth-tracker
- BEA – Regional Price Parities: https://www.bea.gov/data/prices-inflation/regional-price-parities-state-and-metro-area
- BLS - Real Earnings: https://www.bls.gov/news.release/realer.htm

# Data
- R-CPI-I: CPI among different household income quintiles (https://www.bls.gov/cpi/research-series/r-cpi-i.htm)

In [53]:
import pandas

r_cpi_i = pandas.read_excel("data/r-cpi-i-data.xlsx", skiprows=1, header=0)
r_cpi_i.head()

   Year  Month  R-CPI-I1  R-CPI-I2  R-CPI-I3  R-CPI-I4  R-CPI-I5
0  2005     12   100.000   100.000   100.000   100.000   100.000
1  2006      1   100.708   100.745   100.756   100.749   100.805
2  2006      2   100.822   100.908   100.933   100.965   101.123
3  2006      3   101.315   101.418   101.454   101.549   101.775
4  2006      4   102.123   102.268   102.290   102.413   102.594

In [55]:
# Convert df to long format
dfs = []
for quintile in range(1, 6):
    temp = r_cpi_i[['Year', 'Month', f'R-CPI-I{quintile}']].copy()
    temp = temp.rename(columns={f'R-CPI-I{quintile}': 'CPI'})
    temp['Quintile'] = quintile
    dfs.append(temp)

r_cpi_i_long = pandas.concat(dfs, ignore_index=True)
r_cpi_i_long

      Year  Month      CPI  Quintile
0     2005     12  100.000         1
1     2006      1  100.708         1
2     2006      2  100.822         1
3     2006      3  101.315         1
4     2006      4  102.123         1
...    ...    ...      ...       ...
1140  2024      8  157.072         5
1141  2024      9  157.335         5
1142  2024     10  157.526         5
1143  2024     11  157.495         5
1144  2024     12  157.481         5

[1145 rows x 4 columns]

In [ ]:
#TODO: find nominal wage dataset for 5 quintiles (