# Who is hit hardest by Inflation?
**Team Name:** Inflators
- Sanjana Devakumaran *(sanjud)*
- Sanjna Rachakonda *(sanjnarachakonda)*
- Tommy Ayers *(tlayers21)*
- Johnson Hwang *(hjohnson22)*
## Project Introduction
This project will investigate which groups are hit the hardest by inflation in the United States. We will evaluate and compare inflation trends with wage changes across different income levels and industries to understand how inflation affects different parts of the population.
## Research Questions
1. Does inflation affect low-income groups more severely than high-income ones?
2. Do wages keep up with inflation across different industries?
3. Are certain geographical regions hit harder by inflation than others?
## Potential Data Sources
- FRED - Historical Wages With and Without Inflation: https://fred.stlouisfed.org/tags/series?t=inflation;wages
- Atlanta FED - Wage Growth: https://www.atlantafed.org/research-and-data/data/wage-growth-tracker
- BEA – Regional Price Parities: https://www.bea.gov/data/prices-inflation/regional-price-parities-state-and-metro-area
- BLS - Real Earnings: https://www.bls.gov/news.release/realer.htm

# Data
- R-CPI-I: CPI among different household income quintiles (https://www.bls.gov/cpi/research-series/r-cpi-i.htm)

### Loading CPI Data (Income Quintile)

We begin by loading the R-CPI-I dataset, which measures Consumer Price Index (CPI) across different household income quintiles. This dataset allows us to compare how inflation changes over time for different income groups. We intentionally are skipping the first row because it contains context instead of column names. We use the first actual row as the header.

In [ ]:
import pandas

r_cpi_i = pandas.read_excel("data/r-cpi-i-data.xlsx", skiprows=1, header=0)
r_cpi_i.head()

   Year  Month  R-CPI-I1  R-CPI-I2  R-CPI-I3  R-CPI-I4  R-CPI-I5
0  2005     12   100.000   100.000   100.000   100.000   100.000
1  2006      1   100.708   100.745   100.756   100.749   100.805
2  2006      2   100.822   100.908   100.933   100.965   101.123
3  2006      3   101.315   101.418   101.454   101.549   101.775
4  2006      4   102.123   102.268   102.290   102.413   102.594

### Reshaping CPI Data

The original dataset stores CPI values for each income quintile in separate columns in a wide format but we converted it to long format to make the data easier to analyze and visualize. Each row represents a single observation (Year, Month, Quintile). The CPI values are stored in one column instead of multiple columns. The Quintile column, identifies the income group with 1 being the lowest and 5 being the highest. Converting the dataset from wide to long format allows us to easily group, compare, and plot inflation trends across income groups.

In [55]:
# Convert df to long format
dfs = []
for quintile in range(1, 6):
    temp = r_cpi_i[['Year', 'Month', f'R-CPI-I{quintile}']].copy()
    temp = temp.rename(columns={f'R-CPI-I{quintile}': 'CPI'})
    temp['Quintile'] = quintile
    dfs.append(temp)

r_cpi_i_long = pandas.concat(dfs, ignore_index=True)
r_cpi_i_long

      Year  Month      CPI  Quintile
0     2005     12  100.000         1
1     2006      1  100.708         1
2     2006      2  100.822         1
3     2006      3  101.315         1
4     2006      4  102.123         1
...    ...    ...      ...       ...
1140  2024      8  157.072         5
1141  2024      9  157.335         5
1142  2024     10  157.526         5
1143  2024     11  157.495         5
1144  2024     12  157.481         5

[1145 rows x 4 columns]

In [ ]:
#TODO: find nominal wage dataset for 5 quintiles ideally from 2005 - 2024 or nominal wage change

### Loading Mean Income Data by Quintile

To better understand how inflation affects different groups and answer our research question, we also loaded a dataset containing average income values for each income quintile. This data shows that even if inflation rates are similar across groups, lower-income households may be more affected because they have less income to account for rising costs. This dataset will also later allow us to compare inflation trends with income levels. The dataset is loaded directly from an Excel file with standard column headers.

In [7]:
income_quintiles = pandas.read_excel("data/mean_income_quintiles.xlsx", header=0)
income_quintiles

    Year  Income-1  Income-2  Income-3  Income-4  Income-5
0   2005     10660     27360     46300     72830    159580
1   2006     11350     28780     48220     76330    168170
2   2007     11550     29440     49970     79110    167970
3   2008     11660     29520     50130     79760    171060
4   2009     11550     29260     49530     78690    170840
5   2010     10990     28530     49170     78880    169390
6   2011     11240     29200     49840     80080    178020
7   2012     11490     29700     51180     82100    181910
8   2013     11590     30810     53740     86470    193350
9   2014     11680     31090     54040     87830    194050
10  2015     12460     32630     56830     92030    202370
11  2016     12940     34500     59150     95180    213940
12  2017     13260     35400     61560     99030    221850
13  2018     13780     37290     63570    101570    233900
14  2019     15290     40650     68940    111110    254450
15  2020     14590     39480     67850    109730    253480
16  2021     14860     41030     70880    115460    269360
17  2022     16120     43850     74730    119900    277300